export type SceneSearchErrorCode =
  | 'INVALID_NODE_ID'
  | 'DUPLICATE_NODE_DEFINITION'
  | 'UNKNOWN_NODE'
  | 'INVALID_GRANT'
  | 'INVALID_INITIAL_STATE'
  | 'INVALID_WEIGHT'
  | 'WEIGHT_OVERFLOW'
  | 'DUPLICATE_WEIGHTED_DEFINITION'
  | 'INVALID_WEIGHTED_POOL'
  | 'INVALID_INTEL_ID'
  | 'DUPLICATE_INTEL_ID'
  | 'UNKNOWN_SEARCH_DEFINITION'
  | 'INVALID_SCENE_INSTANCE_ID'
  | 'DUPLICATE_INSTANCE_ID'
  | 'ITEM_IDENTITY_MISMATCH'
  | 'NODE_NOT_SEARCHABLE'
  | 'ALREADY_SEARCHED'
  | 'INVALID_SEARCH_STATE'
  | 'INVALID_ILLUMINATION_PROFILE'
  | 'DUPLICATE_ILLUMINATION_PROFILE'
  | 'MISSING_ILLUMINATION_PROFILE'
  | 'UNKNOWN_ILLUMINATION_PROFILE'

export class SceneSearchError extends Error {
  readonly code: SceneSearchErrorCode

  constructor(code: SceneSearchErrorCode, message: string) {
    super(message)
    this.name = 'SceneSearchError'
    this.code = code
  }
}
