export const HOSPITAL_ITEM_IDS = Object.freeze({
  metalPipe: 'weapon_metal_pipe',
  fireAxe: 'weapon_fire_axe',
  heavyCoat: 'armor_heavy_coat',
  crowbar: 'utility_crowbar',
  flashlight: 'utility_flashlight',
  toolkit: 'utility_toolkit',
  bandage: 'consumable_bandage',
  disinfectant: 'consumable_disinfectant',
  firstAidKit: 'consumable_first_aid_kit',
  painkiller: 'consumable_painkiller',
  ration: 'consumable_ration',
  infectionSuppressant: 'consumable_infection_suppressant',
  standardBattery: 'supply_standard_battery',
  metalParts: 'material_metal_parts',
  electronicComponents: 'material_electronic_components',
  fabric: 'material_fabric',
  isolationWardAccessCard: 'access_card_isolation_ward',
  sealedPathogenCase: 'quest_sealed_pathogen_case',
} as const)

export const HOSPITAL_SLICE_ITEM_IDS = Object.freeze([
  HOSPITAL_ITEM_IDS.metalPipe,
  HOSPITAL_ITEM_IDS.fireAxe,
  HOSPITAL_ITEM_IDS.heavyCoat,
  HOSPITAL_ITEM_IDS.crowbar,
  HOSPITAL_ITEM_IDS.flashlight,
  HOSPITAL_ITEM_IDS.toolkit,
  HOSPITAL_ITEM_IDS.bandage,
  HOSPITAL_ITEM_IDS.disinfectant,
  HOSPITAL_ITEM_IDS.firstAidKit,
  HOSPITAL_ITEM_IDS.painkiller,
  HOSPITAL_ITEM_IDS.ration,
  HOSPITAL_ITEM_IDS.infectionSuppressant,
  HOSPITAL_ITEM_IDS.standardBattery,
  HOSPITAL_ITEM_IDS.metalParts,
  HOSPITAL_ITEM_IDS.electronicComponents,
  HOSPITAL_ITEM_IDS.fabric,
  HOSPITAL_ITEM_IDS.isolationWardAccessCard,
  HOSPITAL_ITEM_IDS.sealedPathogenCase,
])
