import type { ItemDefinition } from '../../../core/inventory'
import { HOSPITAL_ITEM_IDS } from './hospital-item-ids'

const none = Object.freeze({ kind: 'none' as const })
const stackable = (maxQuantity: number) =>
  Object.freeze({ kind: 'stackable' as const, maxQuantity })

const definitions: readonly ItemDefinition[] = [
  {
    id: HOSPITAL_ITEM_IDS.metalPipe,
    name: '金属管',
    width: 1,
    height: 3,
    unitWeight: 3,
    canRotate: true,
    stacking: none,
  },
  {
    id: HOSPITAL_ITEM_IDS.fireAxe,
    name: '消防斧',
    width: 2,
    height: 3,
    unitWeight: 5,
    canRotate: true,
    stacking: none,
  },
  {
    id: HOSPITAL_ITEM_IDS.heavyCoat,
    name: '厚实外套',
    width: 2,
    height: 2,
    unitWeight: 2,
    canRotate: true,
    stacking: none,
  },
  {
    id: HOSPITAL_ITEM_IDS.crowbar,
    name: '撬棍',
    width: 1,
    height: 3,
    unitWeight: 3,
    canRotate: true,
    stacking: none,
  },
  {
    id: HOSPITAL_ITEM_IDS.flashlight,
    name: '手电筒',
    width: 1,
    height: 2,
    unitWeight: 1,
    canRotate: true,
    stacking: none,
  },
  {
    id: HOSPITAL_ITEM_IDS.toolkit,
    name: '工具箱',
    width: 2,
    height: 2,
    unitWeight: 4,
    canRotate: true,
    stacking: none,
  },
  {
    id: HOSPITAL_ITEM_IDS.bandage,
    name: '绷带',
    width: 1,
    height: 1,
    unitWeight: 1,
    canRotate: true,
    stacking: stackable(3),
  },
  {
    id: HOSPITAL_ITEM_IDS.disinfectant,
    name: '消毒剂',
    width: 1,
    height: 1,
    unitWeight: 1,
    canRotate: true,
    stacking: stackable(3),
  },
  {
    id: HOSPITAL_ITEM_IDS.firstAidKit,
    name: '急救包',
    width: 1,
    height: 2,
    unitWeight: 2,
    canRotate: true,
    stacking: none,
  },
  {
    id: HOSPITAL_ITEM_IDS.painkiller,
    name: '止痛药',
    width: 1,
    height: 1,
    unitWeight: 1,
    canRotate: true,
    stacking: stackable(3),
  },
  {
    id: HOSPITAL_ITEM_IDS.ration,
    name: '压缩口粮',
    width: 1,
    height: 1,
    unitWeight: 1,
    canRotate: true,
    stacking: stackable(2),
  },
  {
    id: HOSPITAL_ITEM_IDS.infectionSuppressant,
    name: '感染抑制剂',
    width: 1,
    height: 1,
    unitWeight: 1,
    canRotate: true,
    stacking: stackable(2),
  },
  {
    id: HOSPITAL_ITEM_IDS.standardBattery,
    name: '通用电池',
    width: 1,
    height: 1,
    unitWeight: 1,
    canRotate: true,
    stacking: stackable(4),
  },
  {
    id: HOSPITAL_ITEM_IDS.metalParts,
    name: '金属零件',
    width: 1,
    height: 1,
    unitWeight: 1,
    canRotate: true,
    stacking: stackable(5),
  },
  {
    id: HOSPITAL_ITEM_IDS.electronicComponents,
    name: '电子元件',
    width: 1,
    height: 1,
    unitWeight: 1,
    canRotate: true,
    stacking: stackable(5),
  },
  {
    id: HOSPITAL_ITEM_IDS.fabric,
    name: '织物材料',
    width: 1,
    height: 1,
    unitWeight: 1,
    canRotate: true,
    stacking: stackable(5),
  },
  {
    id: HOSPITAL_ITEM_IDS.isolationWardAccessCard,
    name: '隔离区门禁卡',
    width: 1,
    height: 1,
    unitWeight: 0,
    canRotate: true,
    stacking: none,
  },
  {
    id: HOSPITAL_ITEM_IDS.sealedPathogenCase,
    name: '密封病原样本箱',
    width: 2,
    height: 2,
    unitWeight: 4,
    canRotate: true,
    stacking: none,
  },
]

export const hospitalItemDefinitions: readonly Readonly<ItemDefinition>[] =
  Object.freeze(
    definitions.map((definition) =>
      Object.freeze({
        ...definition,
        stacking: Object.freeze({ ...definition.stacking }),
      }),
    ),
  )
